# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       sddm

# >> macros
# << macros

Summary:    Lightweight QML-based display manager
Version:    0.9.0
Release:    1
Group:      System/GUI/Other
License:    LGPL-2.1+
URL:        https://github.com/sddm/sddm
Source0:    %{name}-%{version}.tar.xz
Source100:  sddm.yaml
Source101:  sddm-rpmlintrc
Requires:   xorg-x11-server-Xorg
Requires:   libxcb >= 1.10
Requires:   qt5-plugin-platform-xcb
Requires:   systemd
Requires(preun): systemd
Requires(post): systemd
Requires(postun): systemd
BuildRequires:  pkgconfig(systemd)
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5Gui)
BuildRequires:  pkgconfig(Qt5DBus)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  pkgconfig(Qt5Test)
BuildRequires:  pkgconfig(xcb)
BuildRequires:  pkgconfig(xcb-xkb)
BuildRequires:  cmake
BuildRequires:  pam-devel
BuildRequires:  qt5-qttools-linguist
BuildRequires:  systemd
Provides:   service(graphical-login) = %{name}

%description
Lightweight QML-based display manager.

%prep
%setup -q -n %{name}-%{version}/upstream

# >> setup
# << setup

%build
# >> build pre
# << build pre

%cmake .  \
    -DCMAKE_BUILD_TYPE=RelWithDebInfo

make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# Setup minimum and maximum UID according to /etc/login.defs
uid_min="$(awk 'BEGIN { uid=100000 } /^\s*UID_MIN/ { uid=$2 } END { print uid }' /etc/login.defs 2>/dev/null)"
uid_max="$(awk 'BEGIN { uid=199999 } /^\s*UID_MAX/ { uid=$2 } END { print uid }' /etc/login.defs 2>/dev/null)"
cat > %{buildroot}%{_sysconfdir}/sddm.conf <<EOF
[Users]
MinimumUid=${uid_min}
MaximumUid=${uid_max}
EOF

# Fix pam configuration
sed -i "s/system-login/system-auth/g" %{buildroot}%{_sysconfdir}/pam.d/sddm
sed -i "s/system-local-login/system-auth/g" %{buildroot}%{_sysconfdir}/pam.d/sddm-autologin
sed -i "s/pam_tally.so/pam_tally2.so/g" %{buildroot}%{_sysconfdir}/pam.d/sddm-autologin
# << install post

%pre
# >> pre
# Create sddm user
/usr/sbin/useradd -m -d /var/lib/sddm -s /sbin/nologin -r sddm > /dev/null 2>&1
/usr/sbin/usermod -d /var/lib/sddm -s /sbin/nologin sddm >/dev/null 2>&1
# ignore errors, as we can't disambiguate between sddm already existed
# and couldn't create account with the current adduser.
exit 0
# << pre

%preun
if [ "$1" -eq 0 ]; then
systemctl stop sddm.service
fi
# >> preun
%systemd_preun sddm.service
# << preun

%post
systemctl daemon-reload
systemctl reload-or-try-restart sddm.service
# >> post
%systemd_post sddm.service
# << post

%postun
systemctl daemon-reload
# >> postun
%systemd_postun_with_restart sddm.service
# << postun

%files
%defattr(-,root,root,-)
%config %{_sysconfdir}/sddm.conf
%config(noreplace) %{_sysconfdir}/pam.d/sddm
%config(noreplace) %{_sysconfdir}/pam.d/sddm-autologin
%config(noreplace) %{_sysconfdir}/pam.d/sddm-greeter
%config(noreplace) %{_sysconfdir}/dbus-1/system.d/org.freedesktop.DisplayManager.conf
%{_bindir}/sddm
%{_bindir}/sddm-greeter
%{_libexecdir}/sddm-helper
%{_datadir}/sddm/faces/*
%{_datadir}/sddm/flags/*
%{_datadir}/sddm/scripts/*
%{_datadir}/sddm/translations/*
%{_datadir}/sddm/themes/circles/*
%{_datadir}/sddm/themes/elarun/*
%{_datadir}/sddm/themes/maldives/*
%{_datadir}/sddm/themes/maui/*
%{_unitdir}/sddm.service
%{_libdir}/qt5/qml/SddmComponents/*
# >> files
# << files
