# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       sddm

# >> macros
# << macros

Summary:    Lightweight QML-based display manager
Version:    0.1.0
Release:    1
Group:      System/GUI/Other
License:    LGPL-2.1+
URL:        https://github.com/sddm/sddm
Source0:    %{name}-%{version}.tar.xz
Source100:  sddm.yaml
Source101:  sddm-rpmlintrc
Requires:   weston
Requires:   systemd
Requires(preun): systemd
Requires(post): systemd
Requires(postun): systemd
BuildRequires:  pkgconfig(systemd)
BuildRequires:  pkgconfig(wayland-client)
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5Gui)
BuildRequires:  pkgconfig(Qt5DBus)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  pkgconfig(Qt5Compositor)
BuildRequires:  cmake
BuildRequires:  pam-devel
BuildRequires:  qt5-qttools-linguist

%description
Lightweight QML-based display manager.

%prep
%setup -q -n %{name}-%{version}/upstream

# >> setup
# << setup

%build
# >> build pre
# Get rid of the architecture flag, this will fix arm build
sed -i "s/-march=native//" CMakeLists.txt
# << build pre

%cmake .  \
    -DCMAKE_BUILD_TYPE=RelWithDebInfo \
    -DUSE_QT5:bool=ON \
    -DUSE_WAYLAND:bool=ON \
    -DQTWAYLAND_SCANNER_EXECUTABLE="%{_libdir}/qt5/bin/qtwaylandscanner"

make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post

%preun
if [ "$1" -eq 0 ]; then
systemctl stop sddm.service
fi

%post
systemctl daemon-reload
systemctl reload-or-try-restart sddm.service

%postun
systemctl daemon-reload

%files
%defattr(-,root,root,-)
%config %{_sysconfdir}/sddm.conf
%config(noreplace) %{_sysconfdir}/pam.d/sddm
%config(noreplace) %{_sysconfdir}/dbus-1/system.d/org.freedesktop.DisplayManager.conf
%{_bindir}/sddm
%{_bindir}/sddm-greeter
%{_datadir}/apps/sddm/faces/*
%{_datadir}/apps/sddm/flags/*
%{_datadir}/apps/sddm/scripts/*
%{_datadir}/apps/sddm/translations/*
%{_datadir}/apps/sddm/sddm.conf.sample
%{_datadir}/apps/sddm/themes/circles/*
%{_datadir}/apps/sddm/themes/elarun/*
%{_datadir}/apps/sddm/themes/maldives/*
%{_datadir}/apps/sddm/themes/maui/*
/%{_lib}/systemd/system/sddm.service
%{_libdir}/qt5/qml/SddmComponents/*
# >> files
# << files
